# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25128c6b6a0e1bd02159652fc239190191ec64c1f72ba9baee8dfa46d5f81c7857a773c42c90c7a16d248fb584e35216467f8f9b4531eabfedc4ff8a7996d253

test:
  secret_key_base: eb9868a169a88724fa14e24af3069fb48457e93407dad2137c61163c3cebaf1f0735c22d818ab8900c88e67616de2d85e7eff6c4e1ddc1b17c1abafd5f214f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
